linters:
  disable:
    # Taking advantages of default value, and the author declared "This linter is meant to be used only for special cases. It is not recommended to use it for all files in a project."
    - exhaustivestruct
    # deprecated
    - golint
    # deprecated
    - maligned
    # deprecated
    - interfacer
    # deprecated
    - scopelint
    # I still need to use TODO, FIXME, and others.
    - godox
    # I do not agree with "ireturn", returning interface is the command and basic behavior with OOP.
    - ireturn
    # premature optimization is the root of all evil, DO NOT DO IT!
    - prealloc
    # I have no idea why goimports would wrongly remove my imports, and gci is much better.
    - goimports
  presets:
    # the following presets would actually enable most of (maybe all? I am not sure) the linters.
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - style
    - test
    - unused
issues:
  exclude-use-default: false