linters:
  disable:
    - exhaustivestruct
    - golint
    - maligned
    - interfacer
    - scopelint
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - style
    - test
    - unused