apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kubectl-image-agent
  name: kubectl-image-agent
spec:
  containers:
  - image: ghcr.io/strrl/kubectl-image-agent:latest
    name: kubectl-image-agent
    imagePullPolicy: Always
    volumeMounts:
      - mountPath: /var/run/docker.sock
        name: docker-sock
    resources: {}
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
  restartPolicy: OnFailure
